### ISSUE TITLE
Glot for Docker cloud?

### ISSUE THREAD

**Issue by cezarfloroiu** [prasmussen/glot-run#11]
Hello

Is glot compatible with Docker Cloud?
I managed to install it and to create a user & add a language.  However when I want to run a piece of code it fails , I suspect because it cannot reach the Docker API on port 2375 and there is no way to configure it on the host as I couldnt find the docker config file in etc/default... I'm running Ubunti.

Any idea or suggestion?

Thanks a lot!

**Comment by prasmussen** [comment]
I'm not familiar with docker cloud.

Newer versions of ubuntu uses systemd and the config can be found here: `/lib/systemd/system/docker.service`
Adding the following flag `-H tcp://127.0.0.1:2375` will make the docker daemon listen on port 2375 on localhost. You can test that the connection works by doing `curl http://localhost:2375/version` which should give you a json response. Note that the docker api has no authentication and you probably want to put something in front of it (web proxy / iptables) if you are going to expose it on the network.

**Comment by cezarfloroiu** [comment]
Thx for your answer. It appears to me it is not compatible with Docker cloud.  I will get back to a standard docker installation.
