### ISSUE TITLE
Failed to boot glot

### ISSUE THREAD

**Issue by stephenjesus** [prasmussen/glot-run#25]
Failed to boot glot for reason {{shutdown,
                                                 {failed_to_start_child,
                                                  http_log_srv,
                                                  {{badmatch,{error,eacces}},
                                                   [{http_log_srv,init,1,
                                                     [{file,
                                                       "/home/ubuntu/glot-run/_build/default/lib/glot/src/logging/http_log_srv.erl"},
                                                      {line,25}]},
                                                    {gen_server,init_it,6,
                                                     [{file,"gen_server.erl"},
                                                      {line,328}]},
                                                    {proc_lib,
                                                     init_p_do_apply,3,
                                                     [{file,"proc_lib.erl"},
                                                      {line,240}]}]}}},
                                                {glot_app,start,[normal,[]]}}

**Comment by javierprovecho** [comment]
`badmatch,{error,eacces}` is an error when opening a file, check your filesystem permissions. It can also be that you're trying to listen on a port lower than 1024 without privileges.
