### ISSUE TITLE
I am getting "Missing auth token"  even though i am using a correct one.

### ISSUE THREAD

**Issue by singh-s-sachin** [prasmussen/glot-run#32]
let headers = [
            "Authorization": "f49f383b-0710-494c-ad79-76cdf3970c53",
            "Content-type": "application/json"
        ]
Alamofire.request("https://run.glot.io/languages/python/latest", method: .post, parameters: body , encoding: JSONEncoding.default, headers: headers).responseJSON

this is my code snippet

**Comment by sanjayme97** [comment]
@singh-s-sachin  how did you resolve it?

**Comment by singh-s-sachin** [comment]
Try in this way
let headers : [String : String] = [
            "Content-type": "application/json",
            "Authorization":"f49f383b-0710-494c-ad79-76cdf3970c53"
        ]

**Comment by singh-s-sachin** [comment]
Try in this way
let headers : [String : String] = [
            "Content-type": "application/json",
            "Authorization":"Token f49f383b-0710-494c-ad79-76cdf3970c53"
        ]

**Comment by md-abdul-halim-rafi** [comment]
![image](https://user-images.githubusercontent.com/54027196/99877293-30dbf400-2c27-11eb-994c-c8a4d830bd21.png)

It still saying Missing or wrong access token. I tried with my token, it didn't work. Then I used your one. Still, it doesn't.
