### ISSUE TITLE
Retrieve container stdout

### ISSUE THREAD

**Issue by Dmunch04** [prasmussen/glot-run#39]
Hi!

I was wondering how exactly you're retrieving the Docker container stdout? Do you just read the log file? Because I can't really seem to find where you do that.

Thanks in advance!

**Comment by prasmussen** [comment]
I use the docker api. In this project I'm using the `/containers/:id/attach` endpoint to send stdin and read stdout/stderr.
These days I would recommend using the websocket endpoint instead. It should be easier use: https://docs.docker.com/engine/api/v1.40/#operation/ContainerAttachWebsocket
