### ISSUE TITLE
Why Languages API dont contain "PlainText"?

### ISSUE THREAD

**Issue by aloisdg** [prasmussen/glot-run#4]
Hello,

I guess it is because plain text is not really a language.
How should we use it within the API? I am not sure what to do with it.

Thank you

**Comment by prasmussen** [comment]
It's not listed in the run api since plaintext can't be executed. I would recommend using `plaintext` when saving to the snippets api. Example: [https://snippets.glot.io/snippets/efa8jbdqd3](https://snippets.glot.io/snippets/efa8jbdqd3)

**Comment by aloisdg** [comment]
Ok thank you!
