### ISSUE TITLE
Missing or wrong access token

### ISSUE THREAD

**Issue by md-abdul-halim-rafi** [prasmussen/glot-run#44]
Any of my tokens from the official website is not valid. I always got the error `access_token` with message `Missing or wrong access token`.

**Comment by prasmussen** [comment]
In the image you posted in #32 you have a typo. See if it works if you replace `Tokoen` with `Token`.

**Comment by md-abdul-halim-rafi** [comment]
> In the image you posted in #32 you have a typo. See if it works if you replace `Tokoen` with `Token`.

Ah, silly me! Thanks a ton @prasmussen
